name: architecture_template
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  kartal: ^4.1.0
  vexana: ^5.0.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1

  # Config
  easy_localization: ^3.0.7

  #Utility
  easy_logger: ^0.0.2
  logger: ^2.4.0
  google_fonts: ^6.2.1

  # Modules
  gen:
    path: module/gen
  common:
    path: module/common
  core:
    path: module/core
  widgets:
    path: module/widgets
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  device_preview: ^1.2.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - asset/translations/
